- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- MAINTAINERS.md
- SLACK.md
Added files:
* CODE_OF_CONDUCT
* SLACK
* MAINTAINERS
* CONTRIBUTING
> Readme fixes and additional files

- README.md
Switched badge from looking for a latest release to look for a latest tag.
> fixed latest release badge

- README.md
Add a reference to the policy files. (Feedback from a reviewer).
> added reference to rebac policy template based on reviewer feedback

- go.mod
- go.sum
- pkg/cli/clients/directory_client.go
- pkg/cli/cmd/backup.go
- pkg/cli/cmd/importer.go
- pkg/cli/cmd/load.go
- pkg/cli/cmd/restore.go
Enable topaz CLI to connect to remote topaz instance
> topaz cli remote

- README.md
* added openssf badge
* changed tag to release badge
* added link to demo video
> added openssf best practices badge

- pkg/app/impl/authz.go
fix decision tree, when the request is made without a policy_context.path or empty path, the resulting path_root contains the path of the last iteration.
request
```
{
"identity_context": {
"type": "IDENTITY_TYPE_NONE"
},
"policy_context": {
"path": "",
"decisions": [
"allowed"
]
}
}
```
result before:
```
{
"path_root": "peoplefinder.POST.api.users.__id",
"path": {
"peoplefinder.DELETE.api.users.__id": {
"allowed": false
},
"peoplefinder.GET.api.users": {
"allowed": true
},
"peoplefinder.GET.api.users.__id": {
"allowed": true
},
"peoplefinder.IMPERSONATE.api.users.__id": {
"allowed": false
},
"peoplefinder.POST.api.users": {
"allowed": false
},
"peoplefinder.POST.api.users.__id": {
"allowed": false
},
"peoplefinder.PUT.api.users.__id": {
"allowed": false
}
}
}
```
result after:
```
{ …
```
> fix decisiontree path_root

- go.mod
- go.sum
- go.work.sum
- pkg/cli/cmd/run.go
- pkg/cli/cmd/start.go
- pkg/cli/dockerx/docker.go
fixes https://github.com/aserto-dev/topaz/issues/73
> Mount local store

- .goreleaser.yml
- param .goreleaser.yaml
- .goreleaser
> param goreleaser

- assets/citadel-objects.json
- assets/citadel-relations.json
citadel v2 
updates:
* citadel-objects.json
* citadel-relations.json
to only contain type+key instead of IDs.
> citadel v2

- go.mod
- go.sum
- pkg/app/authorizer.go
- pkg/cc/config/config.go
- pkg/cli/cmd/templates.go
- pkg/testing/assets/config-local.yaml
- pkg/testing/assets/config-online.yaml
depends on: https://github.com/aserto-dev/certs/pull/5
> Update default addresses and dev certs

- pkg/app/impl/jwt.go
fixes https://github.com/aserto-dev/topaz/issues/106
> If identity lookup fails, try looking up a user.

- pkg/cli/cmd/test.go
* set the process exitcode to 1 when test execution failed or errored
* add --summary on topaz test exec displaying the counts like:
```
Test Execution Summary:
-----------------------
total:   28
passed:  27
failed:  1
errored: 0
```
> set exitcode when test failed or errored

- go.mod
- go.sum
- plugins/edge/plugin.go
- plugins/edge/sync.go
refactor edge sync
* populate the cuckoo filter in the producer on a full sync
* diff runs on full sync cycles
* config interval in minutes is divided in 4 cycles, 1 full sync, 3 watermark sync run
* When configured for a 1m interval, this implies:
1. start with a full sync
2. followed by 3 watermark sync
3. running at 1/4 interval of the edge sync configuration interval, implying for a 1 min edge sync config, the interval is 15 secs.
> upd edge sync

- assets/gdrive.json
- assets/gdrive/gdrive_objects.json
- assets/gdrive/gdrive_relations.json
- assets/gdrive/manifest.yml
- assets/gdrive/test/assertions.json
- assets/hosted/gdrive.json
- assets/templates.json
- assets/todo.json
The template creates the following structure:
```
/root/
/root/secrets.txt
/root/rick/
/root/rick/inventions.txt
/root/morty/
/root/morty/morty_private.pdf
/root/morty/shared/
/root/morty/shared/morty_shared.pdf
/root/summer/
/root/jerry/
```
Beth is the owner of the root folder and therefore has full access to everything.
Each user is the owner of their own `/root/<user>/` folder.
Morty has a `/root/morty/shared/` folder that gives editor access to the citadel editor group and viewer to the viewer group.
> Gdrive template

- assets/gdrive.json
- assets/gdrive/gdrive_objects.json
- assets/gdrive/gdrive_relations.json
- assets/gdrive/manifest.yml
- assets/gdrive/test/assertions.json
- assets/hosted/gdrive.json
- assets/templates.json
- assets/todo.json
- go.mod
- go.sum
This PR adds validation logic to ensure that relations being created do not violate the model.
It also revises the GDrive template to use the Citadel user set.
> Validate relations + GDrive template

- go.mod
- go.sum
Use latest self-hosted console release.
> go-topaz-ui v0.0.5

- plugins/edge/plugin.go
- run-now must restart the interval timer
> run-now must restart timer

- README.md
Propagating the enhancement to the Docs quickstart into the corresponding section in the README.
> update readme quickstart to install todo template

- pkg/cc/config/config.go
Reduce the log output caused by the certs generator, which emits arrays of cert files when skipped.
Before 15 lines / 5258 characters
``` json
{"level":"info","component":"config","time":"2024-02-25T22:35:24Z","message":"setting up certs for authorizer"}
{"level":"info","component":"config","existing-files":["/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/gateway.key"],"time":"2024-02-25T22:35:24Z","message":"some cert files already exist, skipping generation"}
{"level":"info","component":"config","time":"2024-02-25T22:35:24Z","message":"setting up certs for model"}
{"level":"info","component":"config","existing-files":["/certs/grpc-ca.crt","/certs/grpc.crt","/certs/grpc.key","/certs/gateway-ca.crt","/certs/gateway.crt","/certs/ …
```
> trim cert generation log msgs

- pkg/cli/cmd/template.go
Add two options to `topaz templates install` to skip running tests and open the console to use it in a CI-like setup to deploy a manifest with data.
`no-tests` skips running the assertions as part of the templates install
`no-console` skips opening the console when the template install is finished
```
topaz3 templates install --help
Usage: topaz templates install --force <name> [<templates-url>]
install template
Arguments:
<name>               template name
[<templates-url>]    URL of template catalog
Flags:
-h, --help                                       Show context-sensitive help.
-N, --no-check                                   disable local container status check ($TOPAZ_NO_CHECK)
-f, --force                                      skip confirmation prompt
--no-tests …
```
> add topaz templates install --no-test --no-console flags

- go.mod
- pkg/app/console.go
- pkg/app/topaz.go
Following the suggestion in https://github.com/aserto-dev/service-host/pull/12#discussion_r1496306978 and after discussions with @carabasdaniel this is a proposal for the redirect to ui from the root that only involves changes in topaz, not in service-host.
> Redirect to ui from root

- cmd/topazd/topaz_run.go
Closes: https://github.com/aserto-dev/topaz/issues/344
> Mark config-file as required flag in topazd

- .github/workflows/ci.yaml
- pkg/cli/cmd/install.go
- pkg/cli/cmd/startrun.go
- pkg/cli/cmd/update.go
- pkg/cli/cmd/version.go
- pkg/cli/dockerx/docker.go
Fix for https://github.com/aserto-dev/topaz/issues/351
> pull image when not present locally

- go.mod
- pkg/cli/xdg/LICENSE
- pkg/cli/xdg/README.md
- pkg/cli/xdg/base_dirs.go
- pkg/cli/xdg/example_test.go
- pkg/cli/xdg/go.mod
- pkg/cli/xdg/go.sum
- pkg/cli/xdg/internal/pathutil/pathutil.go
- pkg/cli/xdg/internal/pathutil/pathutil_test.go
- pkg/cli/xdg/internal/pathutil/pathutil_unix.go
- pkg/cli/xdg/internal/pathutil/pathutil_unix_test.go
- pkg/cli/xdg/internal/pathutil/pathutil_windows.go
- pkg/cli/xdg/internal/pathutil/pathutil_windows_test.go
- pkg/cli/xdg/paths_darwin.go
- pkg/cli/xdg/paths_darwin_test.go
- pkg/cli/xdg/paths_unix.go
- pkg/cli/xdg/paths_unix_test.go
- pkg/cli/xdg/paths_windows.go
- pkg/cli/xdg/paths_windows_test.go
- pkg/cli/xdg/user_dirs.go
- pkg/cli/xdg/xdg.go
- pkg/cli/xdg/xdg_test.go
Update xdg location on Darwin, matching the Unix ones, by adopting the  https://github.com/adrg/xdg  package into the codebase
> use update xdg locations on darwin

- pkg/cli/cmd/directory/test.go
Update test template
```
topaz directory test template
{
"assertions": [
{"check": {"object_type": "", "object_id": "", "relation": "", "subject_type": "", "subject_id": ""}, "expected": true}
]
}
```
> update test template

- assets/api-auth.json
- assets/api-auth/api-auth-objects.json
- assets/api-auth/api-auth-relations.json
- assets/api-auth/ds-load/api-auth.json
- assets/api-auth/manifest.yaml
- assets/api-auth/test/api-auth_assertions.json
- assets/hosted/api-auth.json
- assets/hosted/multi-tenant.json
- assets/multi-tenant.json
- assets/multi-tenant/ds-load/multi-tenant.json
- assets/multi-tenant/manifest.yaml
- assets/multi-tenant/multi-tenant-objects.json
- assets/multi-tenant/multi-tenant-relations.json
- assets/multi-tenant/test/multi-tenant_assertions.json
- assets/templates.json
Added API Authentication template, baselined on the new MT template
> Api auth template

- go.mod
- go.sum
Fixes bug in GetGraph on exclusion permissions
> go-edge-ds v0.32.1

- pkg/cli/cmd/configure/new.go
- pkg/cli/cmd/directory/backup.go
- pkg/cli/cmd/directory/exporter.go
- pkg/cli/cmd/directory/importer.go
- pkg/cli/cmd/directory/restore.go
- pkg/cli/cmd/topaz/install.go
- pkg/cli/cmd/topaz/startrun.go
- pkg/cli/cmd/topaz/status.go
- pkg/cli/cmd/topaz/stop.go
- pkg/cli/cmd/topaz/uninstall.go
- pkg/cli/cmd/topaz/update.go
- pkg/version/version.go
Update the `color` usage to be consistent
> color usage consistency

- assets/multi-tenant/ds-load/multi-tenant.json
- assets/multi-tenant/multi-tenant-objects.json
- assets/multi-tenant/multi-tenant-relations.json
- assets/multi-tenant/test/multi-tenant_assertions.json
* `citadel/adventures` => `citadel-adventures`
* `smiths/budget` => `smiths-budget`
> Replace `/` separator with `-` in multi-tenant template

- go.mod
- go.sum
- pkg/cc/context/context.go
- pkg/cc/signals/signal.go
- pkg/cc/signals/signal_posix.go
- pkg/cc/signals/signal_windows.go
remove sigs.k8s.io/controller-runtime dependency
> remove sigs.k8s.io/controller-runtime dependency

- plugins/edge/plugin.go
Handle edge-sync connection timeout to the remote directory using the edge-sync connection defined timeout.
> edge connection timeout remote directory

- pkg/app/middlewares/middlewares.go
Remove obsolete session-id middleware from topaz service
> remove session-id middleware

- docs/config.md
Small PR - Commit 05bfafbce7ba116fdec7347e69e8816fa29fe678 moved the `plugin.go` file. This PR adjusts sources to changes.
> update configuration source reference

- go.mod
- go.sum
Without circular dependency on topaz (https://github.com/aserto-dev/self-decision-logger/pull/11).
> self-decision-logger v0.0.10

- builtins/edge/ds/relation.go
- go.sum
It only propagates the returned relations, but not objects.
Example with this fix:
**Query**:
```rego
x = ds.relations({
"object_type": "resource",
"object_id": "smiths-budget",
"with_objects": true
})
```
**Result**:
```json
{
"result": [
{
"bindings": {
"x": {
"objects": {
"resource:smiths-budget": {
"created_at": "2024-07-15T15:53:57.916195875Z",
"display_name": "The Smiths family's budget",
"etag": "3002554846938329251",
"id": "smiths-budget",
"properties": {},
"type": "resource",
"updated_at": "2024-07-15T15:53:57.916195875Z"
},
"tenant:smiths": {
"created_at": "2024-07-15T15:53:57.916174958Z",
"display_name": "Smiths tenant",
"etag": "5918144235094477719",
"id": "smiths",
"properties": {},
"type": "tenant",
"updated_at": "2024-07-15T15:53:57.916174958Z"
}, …
```
> ds.relations() returns objects map

- cmd/topaz-db/main.go
- cmd/topaz/main.go
- pkg/app/tests/authz/authz_test.go
- pkg/app/tests/builtin/builtin_test.go
- pkg/app/tests/ds/ds_test.go
- pkg/app/tests/manifest/manifest_test.go
- pkg/app/tests/policy/policy_test.go
- pkg/app/tests/query/query_test.go
- pkg/app/tests/template-no-tls/template-no-tls_test.go
- pkg/app/tests/template/template_test.go
- pkg/app/topaz/runtime_resolver.go
- pkg/cc/config/loader.go
- pkg/cli/cc/client.go
- pkg/cli/cc/container.go
- pkg/cli/cc/dir.go
- pkg/cli/cmd/templates/install.go
- pkg/cli/cmd/templates/list.go
- pkg/cli/cmd/templates/verify.go
- pkg/cli/cmd/topaz/startrun.go
- pkg/cli/dockerx/docker.go
- pkg/cli/fflag/fflag.go
- pkg/cli/x/constants.go
- pkg/cli/x/default.go
- pkg/cli/x/dir.go
- pkg/cli/x/env.go
* add `--templates-url` flag instead of the second positional argument
* refactor embedded strings to const
> tmpl container

- cmd/topaz-db/main.go
- cmd/topaz/main.go
- directory/identity.go
- makefile
- pkg/app/impl/authz.go
- pkg/app/tests/authz/authz_test.go
- pkg/app/tests/builtin/builtin_test.go
- pkg/app/tests/ds/ds_test.go
- pkg/app/tests/manifest/manifest_test.go
- pkg/app/tests/policy/policy_test.go
- pkg/app/tests/query/query_test.go
- pkg/app/tests/template-no-tls/template-no-tls_test.go
- pkg/app/tests/template/template_test.go
- pkg/app/topaz/runtime_resolver.go
- pkg/cc/config/config.go
- pkg/cc/config/loader.go
- pkg/cli/cc/client.go
- pkg/cli/cc/container.go
- pkg/cli/cc/dir.go
- pkg/cli/cmd/templates/install.go
- pkg/cli/cmd/templates/list.go
- pkg/cli/cmd/templates/verify.go
- pkg/cli/cmd/topaz/startrun.go
- pkg/cli/dockerx/docker.go
- pkg/cli/fflag/fflag.go
- pkg/cli/x/constants.go
- pkg/cli/x/default.go
- pkg/cli/x/dir.go
- pkg/cli/x/env.go
* utilize check call to determine the identity resolution direction
* add all v32 and v33 templates to test both TLS and NoTLS template test suites
> dynamic identity resolution direction

- .golangci.yaml
- cmd/topaz-db/cmd/sync.go
- cmd/topaz-db/pkg/inproc/inproc.go
- pkg/app/tests/authz/authz_test.go
- pkg/app/tests/common/common.go
- pkg/app/tests/common/template.go
- pkg/app/tests/ds/checks_test.go
- pkg/app/tests/manifest/manifest_test.go
- pkg/app/tests/policy/policy_test.go
- pkg/app/tests/query/query_test.go
Simplify linter config and fix a few more issues.
> Linter cleanup

- plugins/edge/plugin.go
Fix for https://github.com/aserto-dev/topaz/issues/618
> fix issue-618
